### PR TITLE
Added custom checks, and example checks with tests and read me update

### PR DESCRIPTION
**Pull request by ChrisPhillips-cminion**

### CODE REVIEW

**Comment by dpopp07** [comment]
@ChrisPhillips-cminion Thanks for the PR and for the effort put into it. Before I formally review this, I need to check on a few things. We have some current development underway that involves incorporating custom rules and I need to see how this would or would not fit in with that

**Comment by ChrisPhillips-cminion** [comment]
I have a second pass ready that adds support for regex.

**Comment by jorge-ibm** [comment]
@ChrisPhillips-cminion - We're currently experimenting with adding [Spectral](https://stoplight.io/open-source/spectral/) to our validator. This would give users the ability to add custom rules if they wish. I took a few of the examples you added in the README and translated them to equivalent Spectral rules:
```json
"check-produces-value-case-sensitive": {
			"description": "'produces' object should not contain the value 'application'",
			"type": "style",
			"given": "$.paths..produces.*",
			"severity": "error",
			"formats": ["oas2"],
			"message": "{{path}} contained a value with the invalid string '/produces/'",
			"then": {
				"function": "pattern",
				"functionOptions": {
					"notMatch": "/application/"
				}
			}
		},
		"check-paths-key-case-sensitive": {
			"description": "'info' object should not contain the key 'coolpath'",
			"type": "style",
			"given": "$.paths[*]~",
			"severity": "error",
			"message": "{{path}} contained an invalid string '/coolpath/'",
			"then": {
				"function": "pattern",
				"functionOptions": {
					"notMatch": "/coolpath/"
				}
			}
		},
		"check-info-key-case-sensitive": {
			"description": "'info' object should not contain the key 'testString'",
			"type": "style",
			"given": "$.info[*]~",
			"severity": "error",
			"message": "{{path}} contained an invalid string '/testString/'",
			"then": {
				"function": "pattern",
				"functionOptions": {
					"notMatch": "/testString/"
				}
			}
		},
		"check-info-value-case-insensitive": {
			"description": "'info' object should not contain the value 'testString'",
			"type": "style",
			"given": "$..info.*",
			"severity": "error",
			"message": "{{path}} contained an invalid string '/testString/'",
			"then": {
				"function": "pattern",
				"functionOptions": {
					"notMatch": "/testString/i"
				}
			}
		}
```

Would something like this fit your needs? You can expand each rule as much as you like, or even add new rules if you wish. I pushed a concept branch if you wish to run the linter with a basic integration of spectral: https://github.com/IBM/openapi-validator/tree/spectral-custom-rules against your own api definition.

**Comment by mkistler** [comment]
Closing this PR since the recent addition of Spectral to our validator provides the means to add these custom rules without validator changes.

**Pull request closed without merging**
