### PR TITLE
feat: enable spectral:oas 'no-$ref-siblings' rule

### PR DESCRIPTION
**Pull request by padamstx**
## PR summary
This commit enables the spectral:oas 'no-$ref-siblings'
rule, which checks to make sure that no other
"sibling" properties exist alongside a $ref.

This commit also removes the following legacy rules:
- no_empty_descriptions
- builtin swagger2-specific discriminator-related checks
- $ref_siblings
- duplicate_sibling_description

### General checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [ ] Dependencies have been updated as needed
- [ ] .secrets.baseline updated as needed?

#### Checklist for adding a new validation rule:
- [ ] Added new validation rule definition (packages/ruleset/src/rules/*.js, index.js)
- [ ] If necessary, added new validation rule implementation (packages/ruleset/src/functions/*.js, updated index.js)
- [ ] Added new rule to default configuration (packages/ruleset/src/ibm-oas.js)
- [ ] Added tests for new rule (packages/ruleset/test/*.test.js)
- [ ] Added docs for new rule (docs/ibm-cloud-rules.md)

#### Checklist for removing an old validation rule:
- [x] Removed old rule implementation (packages/validator/src/plugins/validation/*.js)
- [x] Removed or adjusted testcases (packages/validator/test)
- [x] Updated default configuration to deprecate old rule (packages/validator/src/.defaultsForValidator.js)
- [x] Removed docs of old rule (docs/ibm-legacy-rules.md)

### CODE REVIEW

**Review by dpopp07 — APPROVED** [review]
Looks good! 👍

**Review by pyrooka — APPROVED** [review]
LGTM!

**Pull request merged**
