### PR TITLE
Path exclusion

### LINKED ISSUE #294: Any way to suppress specific errors/warnings without completely disabling a rule?
I have an existing spec which has some violations of rules that I would actually like to keep enabled to prevent further violations, but I'd like to ignore the existing ones. Is this currently possible?

### PR DESCRIPTION
**Pull request by Grahahax**
Fixes #294 

Draft to gather feedback on approach.

TODO: Add tests, address feedback etc

### CODE REVIEW

**Comment by dpopp07** [comment]
@Grahahax I apologize for the long delay on reviewing this. We recently had to significantly refactor this tool and wanted to wait until we did that to have a look. That said, I think this seems like a solid approach. The one thing I want to consider before moving forward is [Spectral `overrides`](https://meta.stoplight.io/docs/spectral/ZG9jOjI1MTg5-custom-rulesetsundefined#overrides). This is existing functionality within Spectral that I think meets the criteria you are looking for. We don't currently support it right now but I am working on getting that fixed. If we're able to do that, we would have path exclusions in place for all Spectral-formatted rules (we are working towards moving all validations to this format). If we're not able to get that working, I think we can move forward with this approach. I would just prefer to use existing technology than to add new code to the tool.

**Comment by Grahahax** [comment]
@dpopp07 I would certainly prefer existing technology and if you are moving all validations to spectral format then that sounds like the way to go.

I'll leave this draft open until you decide if you can get all the validations working, at which point we can close or progress this change.

**Comment by dpopp07** [comment]
@Grahahax Sounds good. I have a [PR](https://github.com/IBM/openapi-validator/pull/358) to enable Spectral `overrides` open now. Migrating all of our existing rules will be on ongoing effort but once that PR is merged in, you will be able to exclude specific paths for any Spectral-defined rules

**Comment by dpopp07** [comment]
@Grahahax Thanks again for taking the time to put this together! Now that Spectral overrides are enabled, I'm going to close this draft

**Pull request closed without merging**
