### PR TITLE
fix: vulnerability fix updating package

### PR DESCRIPTION
**Pull request by gopijaganthan**
Purpose:

updating globby package to fix [high vulnerably](https://github.com/advisories/GHSA-ww39-953v-wcq6).

Changes:

Updated globby package from 8 to latest (11.0.4)

Test:
Ran test to ensure the package works as expeceted

Docs:

Hope no docs are requires

### CODE REVIEW

**Review by dpopp07 — APPROVED** [review]
Looks good to me, just need to figure out why the Travis builds aren't finishing

**Comment by dpopp07** [comment]
@gopijaganthan It seems the build failed because of a discrepancy between the `package.json` file and the `package-lock.json` file. Will you update the lock file and commit it with your changes?

**Comment by gopijaganthan** [comment]
> @gopijaganthan It seems the build failed because of a discrepancy between the `package.json` file and the `package-lock.json` file. Will you update the lock file and commit it with your changes?

@dpopp07 Thank you for letting me know.. i will update package-lock.json ad commit it.

**Pull request merged**
