### PR TITLE
fix(validator): Spurious errors when using `application/merge-patch+json` media type

### LINKED ISSUE #197: Spurious errors when using `application/merge-patch+json` media type
Our `PATCH` methods use JSON merge patch semantics -- i.e., `application/merge-patch+json` rather than `application/json`.  However, attempting to use that type results in the following error from the validator:

```
  Message :   Operations with non-form request bodies should set a name with the x-codegen-request-body-name annotation.
  Path    :   paths./dedicated_host/groups/{id}.patch
  Line    :   385
```

This appears to be due to `src/plugins/validation/oas3/semantic-validators/operations.js` having too narrow an understanding of JSON format.  Per https://tools.ietf.org/html/rfc6838#section-4.2.8 any media type ending in `+json` needs to be regarded as being in JSON format.

### PR DESCRIPTION
**Pull request by meem**
Fixes #197.

### CODE REVIEW

**Review by dpopp07 — CHANGES_REQUESTED** [review]
The code looks good to me 👍 Do you mind adding a test to capture this behavior?

I also would like to hear what @mkistler thinks about the change

**Comment by meem** [comment]
@dpopp07 Thanks for the review, and good call on adding a test case.  I added a specific one for this scenario, though I think we may need a broader rework of `operations.test.js` to account for both `application/json` and `+json` throughout.

**Review by mkistler — APPROVED** [review]
Looks good! 👍 

Thanks for the contribution @meem !

**Comment by dpopp07** [comment]
@meem thanks for adding the test - I think this looks good for now. If you would like to add further tests, feel free to open a subsequent PR. Thanks!

**Review by dpopp07 — APPROVED** [review]
Looks good 👍  Thanks for the PR!

**Pull request merged**
