### PR TITLE
feat(schema-type): add new 'schema-type' rule

### LINKED ISSUE #444: Provide rule to check that all schemas have a `type`
With the understanding that some APIs make use of schemas that have no type (i.e., this might default to being optional), our API expects all schemas to have a type, but this is only policed manually at present.  It'd be very helpful to have this enforced by the validator.

### PR DESCRIPTION
**Pull request by dpopp07**
## PR summary

This rule validates that a schema has a non-empty `type` field.

Resolves #444 

### General checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [x] Dependencies have been updated as needed
- [x] .secrets.baseline updated as needed?

#### Checklist for adding a new validation rule:
- [x] Added new validation rule definition (packages/ruleset/src/rules/*.js, index.js)
- [x] If necessary, added new validation rule implementation (packages/ruleset/src/functions/*.js, updated index.js)
- [x] Added new rule to default configuration (packages/ruleset/src/ibm-oas.js)
- [x] Added tests for new rule (packages/ruleset/test/*.test.js)
- [x] Added docs for new rule (docs/ibm-cloud-rules.md)

#### Checklist for removing an old validation rule:
- [ ] Removed old rule implementation (packages/validator/src/plugins/validation/*.js)
- [ ] Removed or adjusted testcases (packages/validator/test)
- [ ] Updated default configuration to deprecate old rule (packages/validator/src/.defaultsForValidator.js)
- [ ] Removed docs of old rule (docs/ibm-legacy-rules.md)

### CODE REVIEW

**Comment by padamstx** [comment]
It's actually valid to not specify the type field for a schema (that's an "any type").   Plus, if a schema has no type field, but specifies "properties", then we have always interpretted that as type=object in the generator (actually down in the swagger-parser I think).
So, I'm not sure we actually want to introduce this rule unless it's disabled by default and individual users can choose to enable it.

**Comment by meem** [comment]
@padamstx Indeed, I commented in #444 that I'd be fine with requiring this rule to be explicitly enabled.  At least in the VPC API, we do not make use of "any" types, and do not want to rely on consumer-specific heuristics such as the presence of `properties` inferring an `object` type.

**Review by padamstx — APPROVED** [review]
LGTM, but we'll need to decide if we're going to make the rule disabled by default or not.  If we do that, we should make sure it is documented as such in the reference docs.

**Review by padamstx — APPROVED** [review]
LGTM

**Pull request merged**
