### PR TITLE
feat: add initial support for openapi 3.1 documents

### PR DESCRIPTION
**Pull request by padamstx**
## PR summary
This commit modifies the validator so that it can be used to validate OpenAPI 3.1 documents.
This initial support does not yet include any
OpenAPI 3.1-specific rules in the IBM Validation Ruleset, so the same rules used to validate OpenAPI 3.0.x documents will be used to validate OpenAPI 3.1.x documents.
An exception to this is the set of rules inherited from the Spectral OAS ruleset, since they do in fact implement some OpenAPI 3.1-specific behavior within those rules.

### General checklist
Please make sure that your PR fulfills the following requirements:  
- [ ] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Dependencies have been updated as needed
- [ ] .secrets.baseline updated as needed?

#### Checklist for adding a new validation rule:
- [ ] Added new validation rule definition (packages/ruleset/src/rules/*.js, index.js)
- [ ] If necessary, added new validation rule implementation (packages/ruleset/src/functions/*.js, updated index.js)
- [ ] Added new rule to default configuration (packages/ruleset/src/ibm-oas.js)
- [ ] Added tests for new rule (packages/ruleset/test/*.test.js)
- [ ] Added docs for new rule (docs/ibm-cloud-rules.md)

### CODE REVIEW

**Review by dpopp07 — APPROVED** [review]
Looks good! 👍

**Comment by padamstx** [comment]
All planned openapi 3.1-related work has completed.  Merging this into main...

**Pull request merged**
