### PR TITLE
fix: false positive when minLength, maxLength are 0

### PR DESCRIPTION
**Pull request by barrett-schonefeld**

### CODE REVIEW

**Review by dpopp07 — APPROVED** [review]
Looks great! Nice add with the min/max length comparison too.

One question - do you think we also need to worry about `null` values? Sometimes `undefined` can be a little prescriptive

**Comment by barrett-schonefeld** [comment]
> One question - do you think we also need to worry about `null` values? Sometimes `undefined` can be a little prescriptive

The API definition would have to explicitly contain a null value, such as `enum: null`, `minLength: null`, `maxLength: null`, etc., to cause a problem, and those seem like invalid values.

**Comment by dpopp07** [comment]
> The API definition would have to explicitly contain a null value (enum: null, minLength: null, maxLength: null, pattern: null) to cause a problem, and that would be invalid for any of these properties

Right, if any of the properties are explicitly set to null, we won't catch them here (they will pass these checks). When you say that would be invalid, do you mean that they are validated somewhere else and so we don't need to worry about that here?

**Comment by barrett-schonefeld** [comment]
> Right, if any of the properties are explicitly set to null, we won't catch them here (they will pass these checks). When you say that would be invalid, do you mean that they are validated somewhere else and so we don't need to worry about that here?

I was thinking it would be covered separately, but now that you pose the question again and I've thought about it more, it would be good to have a helper function here that checks for `null` and `undefined`.

**Review by dpopp07 — APPROVED** [review]
Ah I like the helper function! Looks good 👍

**Pull request merged**
