### PR TITLE
fix: replace isPrimitiveType with more sophisticated isPrimitiveSchema

### PR DESCRIPTION
**Pull request by hudlow**
Signed-off-by: Dan Hudlow <dhudlow@us.ibm.com>

## PR summary
This is mostly @padamstx's work — pulling it out of #506 because this bug is causing me issues in review and that PR still has some open baggage.

### General checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Dependencies have been updated as needed
- [ ] .secrets.baseline updated as needed?

### CODE REVIEW

**Review by padamstx — APPROVED** [review]
LGTM

**Review by dpopp07 — APPROVED** [review]
Looks good! 👍

**Review by dpopp07 — APPROVED** [review]

**Pull request merged**
