### PR TITLE
feat(enum-case-convention): add new enum-case-convention rule, remove old rule

### PR DESCRIPTION
**Pull request by padamstx**
This commit replaces the old enum_case_convention rule with a new
spectral-style enum-case-convention rule that will enforce
the restriction that string-based enum values use snake case.

### CODE REVIEW

**Comment by padamstx** [comment]
@pyrooka, @dpopp07 and I discussed the case convention topic today and decided to hard-code the enum-case-convention and property-case-convention rules so they enforce snake-case.  This was mainly due to how difficult it is for users to change the configuration of one of our rules, so we went with just implementing the rules to enforce snake-case.
This PR has been updated to reflect those changes.

**Review by pyrooka — APPROVED** [review]
Still looks good! :)

**Comment by padamstx** [comment]
Re-based this PR on top of the "staging" branch.

**Comment by padamstx** [comment]
Discussed the case convention stuff with @dpopp07 again yesterday and we decided to reverse our earlier decision...  so the enum-case-convention and property-case-convention rules have been updated slightly to get the "casing config" from the rule definition.   Both rules are now configured to use snake case by default, but a user could override that by re-defining the rule in their custom ruleset and changing the config to a different casing style.

**Review by dpopp07 — APPROVED** [review]
Looks good! 👍

**Pull request merged**
