### PR TITLE
fix: use single logger instance

### PR DESCRIPTION
**Pull request by padamstx**
## PR summary
This PR makes sure that the validator and all rules use a single global instance of the LoggerFactory.

### General checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [x] Dependencies have been updated as needed
- [ ] .secrets.baseline updated as needed?

#### Checklist for adding a new validation rule:
- [ ] Added new validation rule definition (packages/ruleset/src/rules/*.js, index.js)
- [ ] If necessary, added new validation rule implementation (packages/ruleset/src/functions/*.js, updated index.js)
- [ ] Added new rule to default configuration (packages/ruleset/src/ibm-oas.js)
- [ ] Added tests for new rule (packages/ruleset/test/*.test.js)
- [ ] Added docs for new rule (docs/ibm-cloud-rules.md)

### CODE REVIEW

**Review by dpopp07 — APPROVED** [review]
Looks good!

I noticed the line `static _factory = null;` is still present in the logger factory file, which I don't think will be used anymore. I'd recommend taking it out before merging but otherwise, good to go 👍

**Comment by padamstx** [comment]
> Looks good!
> 
> I noticed the line `static _factory = null;` is still present in the logger factory file

good catch... with all the excitement related to this PR I completely whiffed at removing that line :joy:

**Pull request merged**
